REM   Script: Session 01
REM   EMPLOYEE  AND DEPARTMENT TABLE

create table employee_01  
(EMPL_NO NUMBER PRIMARY KEY,EMP_NAME VARCHAR(50),JOB VARCHAR(70),MANAGER_NO NUMBER,SALARY NUMBER );

INSERT INTO EMPLOYEE_01 
VALUES(101,'Dhruv','Accountant','1','100000') 
;

INSERT INTO EMPLOYEE_01 
VALUES(102,'Riddhi','Legal','2','200000') 
;

INSERT INTO EMPLOYEE_01 
VALUES(103,'Jatin','Sales','3','400000') 
;

INSERT INTO EMPLOYEE_01 
VALUES(104,'Gungun','Media','4','300000') 
;

CREATE TABLE DEPARTMENT_01 
(DEPT_NO NUMBER,DEPT_NAME VARCHAR2(50),DLOC VARCHAR2(40));

INSERT INTO EMPLOYEE_01 
VALUES(105,'Srishti','Product Managment','4','300000') 
;

select*from employee_01 
;

UPDATE EMPLOYEE_01 
SET JOB='Trading' 
where EMPL_NO=103;

DELETE FROM EMPLOYEE_01 
WHERE EMPL_NO=105;

SELECT*FROM EMPLOYEE_01;

INSERT INTO DEPARTMENT_01 
VALUES(01,'Accountant','Lajpat Nager');

INSERT INTO DEPARTMENT_01 
VALUES(02,'Finance','Okhala');

INSERT INTO DEPARTMENT_01 
VALUES(03,'Sales','Dehradun');

select*from department_01;

update department_01 
set DLOC='A-BLOCK' 
WHERE DEPT_NO=1;

update department_01 
set DLOC='C-BLOCK' 
WHERE DEPT_NO=3;

update department_01 
set DLOC='B-BLOCK' 
WHERE DEPT_NO=2;

SELECT * FROM DEPARTMENT_01;

UPDATE DEPARTMENT_01 
SET DEPT_NAME='ACCOUNTANT' 
WHERE DEPT_NO=3;

